stages:
  - build_server
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  REGISTRY: "mathinstitut"

# gitlab ci script taken from https://gist.github.com/danielneis/5c6140ec8150c6151a54bccd26950278

build_server_binary:
  stage: build_server
  image: golang
  tags:
    - docker
  script:
    - ./buildweb.sh
  artifacts:
    paths:
    - bin/web
    expire_in: 1 week

build_goemaxima_containers:
  image: "docker:latest"
  stage: build
  tags:
    - docker
  before_script:
    - docker login -u mathinstitut -p "$DOCKERHUB_PASS" registry-1.docker.io
  script:
    - ./build.sh "$REGISTRY" "$CI_COMMIT_TAG"

build_gitrollout:
  image: "docker:latest"
  stage: build
  tags:
    - docker
  before_script:
    - docker login -u mathinstitut -p "$DOCKERHUB_PASS"
  script:
    - docker build -t mathinstitut/git-rollout:latest git-rollout
    - docker push mathinstitut/git-rollout:latest
  only:
    changes:
      - git-rollout/**
      - .gitlab-ci.yml
