version: "3.9"
services:
  maxima:
    image: mathinstitut/goemaxima:${STACKMAXIMA_VERSION:-2023010400}-latest
    ports:
      - 0.0.0.0:8080:8080
    tmpfs:
      - "/tmp"
    restart: unless-stopped
    cap_add:
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    read_only: true
