version: "3.9"
services:
  maxima:
    image: mathinstitut/goemaxima:${STACKMAXIMA_VERSION:-2021120900}-latest
    ports:
      - 0.0.0.0:8080:8080
    tmpfs:
      - "/tmp"
    restart: unless-stopped
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - KILL
    cap_drop:
      - ALL
    read_only: true
