version: "3.9"
services:
  maxima:
    image: goemaxima:${STACKMAXIMA_VERSION:-2021120900}-dev
    ports:
      - 8765:8080
    tmpfs:
      - "/tmp"
    restart: unless-stopped
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - KILL
    cap_drop:
      - ALL
    read_only: true
