apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helmmaxima.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helmmaxima.fullname" . }}
  minReplicas: {{ .Values.scaleMin }}
  maxReplicas: {{ .Values.scaleMax }}
  targetCPUUtilizationPercentage: {{ .Values.scalePercentage }}
