apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmmaxima.fullname" . }}
  labels:
    {{ if .Values.enableGitRollout -}}
    gitrollout: goemaxima
    {{- end -}}
    {{- include "helmmaxima.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helmmaxima.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helmmaxima.selectorLabels" . | nindent 8 }}
        app: {{ include "helmmaxima.fullname" . }}
    spec:
      terminationGracePeriodSeconds: 45
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      automountServiceAccountToken: false
      {{ if .Values.enableGitRollout }}
      initContainers:
        - name: "{{ .Chart.Name }}-git"
          image: "k8s.gcr.io/git-sync/git-sync:v3.6.1"
          args: ['--root=/mnt', '--one-time', '--depth=1']
          volumeMounts:
            - mountPath: /mnt
              name: git
          env:
            - name: GIT_SYNC_REPO
              value: "{{ .Values.gitRollout.repo }}"
            - name: GIT_SYNC_BRANCH
              value: "{{ .Values.gitRollout.branch }}"
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.image_prefix }}:{{ .Values.stackver }}-{{ .Values.tagappend | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmptmpfs
            {{ if .Values.enableGitRollout }}
            - mountPath: /mnt
              name: git
            {{ end }}
          livenessProbe:
            httpGet:
              path: '/maxima?health=1'
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: '/maxima?health=1'
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          {{ if .Values.enableGitRollout }}
          env:
            - name: GOEMAXIMA_EXTRA_PACKAGES
              value: "{{ .Values.gitRollout.includefile }}"
          {{ end }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "35"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tmptmpfs
          emptyDir:
            medium: "Memory"
        {{ if .Values.enableGitRollout }}
        - name: git
          emptyDir:
            medium: "Memory"
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
