apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "helmmaxima.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "helmmaxima.fullname" . }}
  # block egress traffic
  policyTypes:
  - Egress
  {{ if .Values.enableGitRollout }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: git-rollout
    - ports:
        - protocol: TCP
          port: 9418
  {{ end }}
