apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "helmmaxima.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "helmmaxima.fullname" . }}
  # block all egress traffic
  policyTypes:
  - Egress
