# Default values for helmmaxima.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

scalePercentage: 40
scaleMin: 3
scaleMax: 32

# whether to include the coreos monitor resource for prometeus metrics
monitor: true

image:
  image_prefix: mathinstitut/goemaxima
  pullPolicy: Always

enableGitRollout: false

gitRollout:
  repo: 'git://$(GIT_ROLLOUT_SERVICE_HOST)/git'
  branch: main
  includefile: '/mnt/git/main.mac'

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

disableRoot: false

securityContext:
  capabilities:
    add:
    - SETGID
    - SETUID
    drop:
    - ALL
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /goemaxima
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 1000m
    memory: 256Mi

# maximum size of /tmp
tmpfsSizeLimit: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
